### ISSUE TITLE
Game Keeps on showing 1 and doesnt start | Version: 1.16.1

### ISSUE THREAD

**Issue by Thundertides** [pronze/SBAHypixelify#1]
Console Error:
```Java 
[19:58:16 WARN]: [BedWars] Task #247380 for BedWars v0.2.11 generated an exception
java.lang.NullPointerException: null
        at org.screamingsandals.bedwars.game.Game.run(Game.java:1608) ~[?:?]
        at org.screamingsandals.bedwars.game.Game$7.run(Game.java:2108) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-43]
        at java.lang.Thread.run(Thread.java:834) [?:?] 
```

Plugins:

```Luckperms, WorldEdit, ViaVersion, VoidGenerator, Vault, Essentials, ViaBackwards, EssentialsChat, Multiverse-Core, BedWars, TAB, SBAHypixelify```

Problem:
During the countdown the game will be stuck at 1

[SBAHypixelifyconfig.zip](https://github.com/pronze/SBAHypixelify/files/4899256/SBAHypixelifyconfig.zip)

**Comment by Thundertides** [comment]
This was fixed by readding a material that the plugin removed from the original file
