### ISSUE TITLE
ERROR Could not pass event PlayerLoginEvent to SBAHypixelify

### ISSUE THREAD

**Issue by Vidhin05** [pronze/SBAHypixelify#125]
Version: Hypixelify CI#177, Bedwars CI#803, Java11, Purpur 1.16.5
Log:
[06:41:38 ERROR]: Could not pass event PlayerLoginEvent to SBAHypixelify v2.0.0-SNAPSHOT
java.lang.NullPointerException: null
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:418) ~[?:?]
        at com.comphenix.tinyprotocol.Reflection$1.get(Reflection.java:153) ~[?:?]
        at com.comphenix.tinyprotocol.TinyProtocol.getChannel(TinyProtocol.java:279) ~[?:?]
        at com.comphenix.tinyprotocol.TinyProtocol.access$900(TinyProtocol.java:30) ~[?:?]
        at com.comphenix.tinyprotocol.TinyProtocol$5.onPlayerLogin(TinyProtocol.java:166) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.16.5.jar:git-Purpur-1125]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1125]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1125]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:619) ~[patched_1.16.5.jar:git-Purpur-1125]
        at net.minecraft.server.v1_16_R3.PlayerList.attemptLogin(PlayerList.java:771) ~[patched_1.16.5.jar:git-Purpur-1125]
        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:170) ~[patched_1.16.5.jar:git-Purpur-1125]
        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:87) ~[patched_1.16.5.jar:git-Purpur-1125]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:583) ~[patched_1.16.5.jar:git-Purpur-1125]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:164) ~[patched_1.16.5.jar:git-Purpur-1125]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1596) ~[patched_1.16.5.jar:git-Purpur-1125]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.16.5.jar:git-Purpur-1125]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1415) ~[patched_1.16.5.jar:git-Purpur-1125]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1141) ~[patched_1.16.5.jar:git-Purpur-1125]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1125]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[06:41:38 INFO]: [SBAHypixelify] Registered player: Vidhin

**Comment by zlataovce** [comment]
we already told you at the discord server that we do not support snapshots of bw and sba
