### ISSUE TITLE
Plugin will not load (NullPointerException)

### ISSUE THREAD

**Issue by Thundertides** [pronze/SBAHypixelify#2]
```Java

[01:22:31 ERROR]: Error occurred while enabling SBAHypixelify v1.1.4 (Is it up to date?)
java.lang.NullPointerException: null
        at org.screamingsandals.bedwars.lib.sgui.utils.StackParser.parse(StackParser.java:52) ~[?:?]
        at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.generateItem(SimpleInventories.java:706) ~[?:?]
        at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.generateItem(SimpleInventories.java:912) ~[?:?]
        at org.screamingsandals.bedwars.lib.sgui.SimpleInventories.generateData(SimpleInventories.java:323) ~[?:?]
        at org.pronze.hypixelify.inventories.customShop.loadNewShop(customShop.java:377) ~[?:?]
        at org.pronze.hypixelify.inventories.customShop.<init>(customShop.java:159) ~[?:?]
        at org.pronze.hypixelify.Hypixelify.onEnable(Hypixelify.java:68) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-43]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-43]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.reload(CraftServer.java:932) ~[patched_1.16.1.jar:git-Paper-43]
        at org.bukkit.Bukkit.reload(Bukkit.java:688) ~[patched_1.16.1.jar:git-Paper-43]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.1.jar:git-Paper-43]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-43]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-43]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-43]
```

It might have something to do with Netherite? I put the configs in the other issue I created

**Comment by pronze** [comment]
Try using the latest version 1.2.2 and tell me if this issue persists.

**Comment by Thundertides** [comment]
The null pointer exception persists

**Comment by pronze** [comment]
Do /bwaddon reset then and try again. You must have messed with the config somehow. Also what server version are you running?

**Comment by RMantis** [comment]
`at org.pronze.hypixelify.inventories.customShop.loadNewShop(customShop.java:377) ~[?:?]` - happened to me when I messed up the shop config, 90% its the same problem.

@pronze maybe we should add a check and a clear console message for that error?

P.S. I said "we" because I'm thinking about contributing to this project :)

**Comment by pronze** [comment]
Feel free to contribute to this project via pull requests, I've been shifting my focus to some other project currently and won't have much time soon. Your PR's would be helpful to the plugin users :)

Closing issue
