### ISSUE TITLE
Can't run with build 732 of BedWars

### ISSUE THREAD

**Issue by kotyk7** [pronze/SBAHypixelify#73]
[Purpur 978](https://github.com/pl3xgaming/Purpur/commit/9537c770b0820b8b7a9915a7d571de528dc5ce8c), [Bedwars #732](https://ci.screamingsandals.org/job/BedWars-0.x.x/732/)

It throws "NoSuchMethodError" while enabling
Log provided below
```[17:46:00] [Server thread/INFO]: Time elapsed: 433 ms
[17:46:00] [Server thread/INFO]: [BedWars] Enabling BedWars v0.3.0-SNAPSHOT
[17:46:00] [Server thread/INFO]: [BedWars] Successfully loaded messages for BedWars! Language: English
[17:46:00] [Server thread/INFO]: [BedWars] Loading statistics from YAML-File ...
[17:46:00] [Server thread/INFO]: =====================  by ScreamingSandals <Misat11, Ceph, Pronze>[m
[17:46:00] [Server thread/INFO]: + Screaming BedWars +  Version: 0.3.0-SNAPSHOT FREE[m
[17:46:00] [Server thread/INFO]: =====================  SNAPSHOT VERSION (731) - Use at your own risk[m
[17:46:00] [Server thread/INFO]: Everything is loaded! If you like our work, consider visiting our Patreon! <3[m
[17:46:00] [Server thread/INFO]: https://www.patreon.com/screamingsandals[m
[17:46:00] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.4.6
[17:46:00] [Server thread/INFO]: [HolographicDisplays] Enabled player relative placeholders with ProtocolLib.
[17:46:00] [Server thread/INFO]: [SBAHypixelify] Enabling SBAHypixelify v1.4.3
[17:46:00] [Server thread/INFO]: [SBAHypixelify]: &a Detected first start
[17:46:00] [Server thread/ERROR]: Error occurred while enabling SBAHypixelify v1.4.3 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.screamingsandals.bedwars.config.Configurator org.screamingsandals.bedwars.Main.getConfigurator()'
	at io.pronze.hypixelify.Configurator.upgradeCustomFiles(Configurator.java:532) ~[?:?]
	at io.pronze.hypixelify.Configurator.loadDefaults(Configurator.java:507) ~[?:?]
	at io.pronze.hypixelify.SBAHypixelify.onEnable(SBAHypixelify.java:142) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-978]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-978]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-978]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.5.jar:git-Purpur-978]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:467) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:249) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:942) ~[patched_1.16.5.jar:git-Purpur-978]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[patched_1.16.5.jar:git-Purpur-978]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[17:46:00] [Server thread/INFO]: [SBAHypixelify] Disabling SBAHypixelify v1.4.3
[17:46:00] [Server thread/INFO]: [SBAHypixelify] Cancelling current tasks....
[17:46:00] [Server thread/INFO]: Running delayed init tasks
[17:46:00] [Server thread/INFO]: Done (2.870s)! For help, type "help"```

**Comment by kotyk7** [comment]
Only dependency I didn't have was PaPI

**Comment by kotyk7** [comment]
Seems to launch with Bedwars build 726

**Comment by kotyk7** [comment]
Nevermind, I didn't read the Discord announcements
